import type { DomainMeta } from "./types";

export const DOMAINS: DomainMeta[] = [
  {
    id: "people",
    href: "/people",
    title: "People & Society",
    titleNp: "जनसंख्या",
    blurb: "Population, vitals, literacy, HDI",
    accent: "#3DDC97",
  },
  {
    id: "economy",
    href: "/economy",
    title: "Economy & Markets",
    titleNp: "अर्थतन्त्र",
    blurb: "GDP, FX, remittance, NEPSE, CPI",
    accent: "#F4D35E",
  },
  {
    id: "government",
    href: "/government",
    title: "Government & Finance",
    titleNp: "सरकार",
    blurb: "Cabinet roster, budget, revenue, fiscal transfers",
    accent: "#E8A87C",
  },
  {
    id: "health",
    href: "/health",
    title: "Health",
    titleNp: "स्वास्थ्य",
    blurb: "Facilities, mortality, immunization",
    accent: "#41B3A3",
  },
  {
    id: "education",
    href: "/education",
    title: "Education",
    titleNp: "शिक्षा",
    blurb: "Schools, enrollment, outcomes",
    accent: "#7BDFF2",
  },
  {
    id: "energy",
    href: "/energy",
    title: "Energy & Infrastructure",
    titleNp: "ऊर्जा",
    blurb: "Hydro capacity, electrification, fuel",
    accent: "#FF9F1C",
  },
  {
    id: "environment",
    href: "/environment",
    title: "Environment & Climate",
    titleNp: "वातावरण",
    blurb: "AQI, monsoon, forests, rivers",
    accent: "#2EC4B6",
  },
  {
    id: "disasters",
    href: "/disasters",
    title: "Disasters & Safety",
    titleNp: "प्रकोप",
    blurb: "Floods, landslides, fire, quakes, river alerts",
    accent: "#FF6B6B",
  },
  {
    id: "tourism",
    href: "/tourism",
    title: "Tourism & Culture",
    titleNp: "पर्यटन",
    blurb: "Arrivals, hotels, travel income",
    accent: "#CDB4DB",
  },
  {
    id: "digital",
    href: "/digital",
    title: "Connectivity & Digital",
    titleNp: "डिजिटल",
    blurb: "Mobile, broadband, bandwidth",
    accent: "#4CC9F0",
  },
  {
    id: "transport",
    href: "/transport",
    title: "Transport & Mobility",
    titleNp: "यातायात",
    blurb: "Vehicles, EV share, aviation",
    accent: "#90BE6D",
  },
  {
    id: "agriculture",
    href: "/agriculture",
    title: "Agriculture & Food",
    titleNp: "कृषि",
    blurb: "Cereals, livestock, kitchen prices",
    accent: "#B5E48C",
  },
  {
    id: "migration",
    href: "/migration",
    title: "Labor & Migration",
    titleNp: "वैदेशिक रोजगार",
    blurb: "Outflows, destinations, remittance link",
    accent: "#F72585",
  },
  {
    id: "places",
    href: "/places",
    title: "Places",
    titleNp: "स्थानहरू",
    blurb: "Map layers and district drill-down",
    accent: "#A0C4FF",
  },
  {
    id: "news",
    href: "/news",
    title: "News & Calendar",
    titleNp: "समाचार",
    blurb: "Local headlines and release calendar",
    accent: "#FFB703",
  },
];

export const PROVINCE_NAMES: Record<number, { en: string; np: string }> = {
  1: { en: "Koshi", np: "कोशी" },
  2: { en: "Madhesh", np: "मधेश" },
  3: { en: "Bagmati", np: "बागमती" },
  4: { en: "Gandaki", np: "गण्डकी" },
  5: { en: "Lumbini", np: "लुम्बिनी" },
  6: { en: "Karnali", np: "कर्णाली" },
  7: { en: "Sudurpashchim", np: "सुदूरपश्चिम" },
};
