import type { DomainId, Metric } from "../types";

/** Curated national figures from published NSO/NRB/NTB/NTA/MoHP-style releases.
 *  Live connectors overwrite FX, quakes, and news at runtime. Always show source + asOf.
 */
export const CENSUS_POPULATION_2021 = 29_164_578;
export const POP_GROWTH_RATE = 0.0092; // ~0.92% annual (UN/NSO mid-range)
export const CENSUS_DATE = new Date("2021-11-25T00:00:00Z");

export function estimatePopulation(now = new Date()): number {
  const years =
    (now.getTime() - CENSUS_DATE.getTime()) / (365.25 * 24 * 3600 * 1000);
  return Math.round(CENSUS_POPULATION_2021 * Math.exp(POP_GROWTH_RATE * years));
}

export const DOMAIN_METRICS: Record<DomainId, Metric[]> = {
  people: [
    {
      key: "pop_census",
      label: "Census population (2021)",
      value: CENSUS_POPULATION_2021,
      freshness: "P",
      source: "NSO NPHC 2021",
      asOf: "2021-11-25",
      format: "number",
    },
    {
      key: "households",
      label: "Households",
      value: 6_666_937,
      freshness: "P",
      source: "NSO NPHC 2021",
      asOf: "2021-11-25",
      format: "compact",
    },
    {
      key: "avg_hh",
      label: "Avg household size",
      value: 4.37,
      freshness: "P",
      source: "NSO NPHC 2021",
      asOf: "2021-11-25",
      format: "raw",
    },
    {
      key: "sex_ratio",
      label: "Sex ratio (M per 100 F)",
      value: 95.6,
      freshness: "P",
      source: "NSO NPHC 2021",
      asOf: "2021-11-25",
      format: "raw",
    },
    {
      key: "literacy",
      label: "Literacy rate (5+)",
      value: 76.2,
      unit: "%",
      freshness: "P",
      source: "NSO NPHC 2021",
      asOf: "2021-11-25",
      format: "percent",
    },
    {
      key: "urban_share",
      label: "Urban population share",
      value: 66.2,
      unit: "%",
      freshness: "P",
      source: "NSO NPHC 2021",
      asOf: "2021-11-25",
      format: "percent",
      description: "Includes municipalities under federal structure",
    },
    {
      key: "cbr",
      label: "Crude birth rate",
      value: 19.8,
      unit: "per 1,000",
      freshness: "P",
      source: "UN WPP / NSO",
      asOf: "2024",
      format: "raw",
    },
    {
      key: "cdr",
      label: "Crude death rate",
      value: 6.3,
      unit: "per 1,000",
      freshness: "P",
      source: "UN WPP / NSO",
      asOf: "2024",
      format: "raw",
    },
    {
      key: "life_exp",
      label: "Life expectancy",
      value: 71.2,
      unit: "years",
      freshness: "P",
      source: "UN WPP",
      asOf: "2024",
      format: "raw",
    },
    {
      key: "hdi",
      label: "Human Development Index",
      value: 0.601,
      freshness: "P",
      source: "UNDP HDR",
      asOf: "2023/24",
      format: "raw",
    },
  ],
  economy: [
    {
      key: "gdp_growth",
      label: "GDP growth (est.)",
      value: 3.85,
      unit: "%",
      freshness: "P",
      source: "NRB / NSO",
      asOf: "FY 2025/26",
      format: "percent",
    },
    {
      key: "cpi",
      label: "CPI inflation (yoY)",
      value: 5.14,
      unit: "%",
      freshness: "NR",
      source: "NRB",
      asOf: "mid-July 2026",
      format: "percent",
    },
    {
      key: "remittance",
      label: "Remittance (FY)",
      value: 2363.13,
      unit: "bn NPR",
      delta: 37.1,
      deltaLabel: "YoY",
      freshness: "P",
      source: "NRB",
      asOf: "FY 2025/26",
      format: "raw",
    },
    {
      key: "reserves",
      label: "FX reserves",
      value: 25.31,
      unit: "bn USD",
      freshness: "P",
      source: "NRB",
      asOf: "mid-July 2026",
      format: "raw",
    },
    {
      key: "import_cover",
      label: "Import cover",
      value: 19.6,
      unit: "months",
      freshness: "P",
      source: "NRB",
      asOf: "mid-July 2026",
      format: "raw",
    },
    {
      key: "exports_growth",
      label: "Exports growth",
      value: 13.8,
      unit: "%",
      freshness: "P",
      source: "NRB",
      asOf: "FY 2025/26",
      format: "percent",
    },
    {
      key: "imports_growth",
      label: "Imports growth",
      value: 16.2,
      unit: "%",
      freshness: "P",
      source: "NRB",
      asOf: "FY 2025/26",
      format: "percent",
    },
    {
      key: "nepse",
      label: "NEPSE index",
      value: 2684.5,
      freshness: "NR",
      source: "NEPSE (indicative)",
      asOf: "latest session",
      format: "number",
    },
    {
      key: "gdp_pc",
      label: "GDP per capita",
      value: 1456,
      unit: "USD",
      freshness: "P",
      source: "World Bank / NSO",
      asOf: "2024",
      format: "number",
    },
  ],
  government: [
    {
      key: "revenue_ytd",
      label: "Federal revenue (indicative FY)",
      value: 1120,
      unit: "bn NPR",
      freshness: "P",
      source: "MoF / FCGO",
      asOf: "FY recent",
      format: "raw",
    },
    {
      key: "expenditure_ytd",
      label: "Federal expenditure",
      value: 1450,
      unit: "bn NPR",
      freshness: "P",
      source: "MoF / FCGO",
      asOf: "FY recent",
      format: "raw",
    },
    {
      key: "vat_share",
      label: "VAT share of tax",
      value: 38,
      unit: "%",
      freshness: "P",
      source: "IRD / MoF",
      asOf: "FY recent",
      format: "percent",
    },
    {
      key: "transfers",
      label: "Transfers to PLGs",
      value: 420,
      unit: "bn NPR",
      freshness: "P",
      source: "WB Fiscal / FCGO",
      asOf: "FY recent",
      format: "raw",
    },
    {
      key: "capital_share",
      label: "Capital spending share",
      value: 18,
      unit: "%",
      freshness: "P",
      source: "MoF",
      asOf: "FY recent",
      format: "percent",
    },
    {
      key: "deficit",
      label: "Fiscal deficit (of GDP)",
      value: 4.2,
      unit: "%",
      freshness: "P",
      source: "MoF",
      asOf: "FY recent",
      format: "percent",
    },
  ],
  health: [
    {
      key: "facilities",
      label: "Health facilities",
      value: 7500,
      freshness: "P",
      source: "MoHP / National Data Portal",
      asOf: "latest",
      format: "compact",
    },
    {
      key: "doctors_10k",
      label: "Doctors per 10k",
      value: 8.9,
      freshness: "P",
      source: "MoHP",
      asOf: "latest",
      format: "raw",
    },
    {
      key: "nurses_10k",
      label: "Nurses/midwives per 10k",
      value: 36,
      freshness: "P",
      source: "MoHP",
      asOf: "latest",
      format: "raw",
    },
    {
      key: "mmr",
      label: "Maternal mortality ratio",
      value: 151,
      unit: "per 100k live births",
      freshness: "P",
      source: "MoHP / NDHS",
      asOf: "latest survey",
      format: "raw",
    },
    {
      key: "u5mr",
      label: "Under-5 mortality",
      value: 27,
      unit: "per 1,000",
      freshness: "P",
      source: "NDHS / MoHP",
      asOf: "latest survey",
      format: "raw",
    },
    {
      key: "stunting",
      label: "Child stunting",
      value: 25,
      unit: "%",
      freshness: "P",
      source: "NDHS",
      asOf: "latest survey",
      format: "percent",
    },
    {
      key: "immunization",
      label: "Full immunization coverage",
      value: 78,
      unit: "%",
      freshness: "P",
      source: "MoHP",
      asOf: "latest",
      format: "percent",
    },
    {
      key: "tfr",
      label: "Total fertility rate",
      value: 2.0,
      freshness: "P",
      source: "NDHS / NSO",
      asOf: "latest",
      format: "raw",
    },
  ],
  education: [
    {
      key: "schools",
      label: "Schools (all levels)",
      value: 35000,
      freshness: "P",
      source: "CEHRD IEMIS Flash",
      asOf: "AY 2082",
      format: "compact",
    },
    {
      key: "ece",
      label: "ECE centers",
      value: 42619,
      freshness: "P",
      source: "CEHRD Flash 2082",
      asOf: "2025/26",
      format: "number",
    },
    {
      key: "basic_enr",
      label: "Basic enrollment (indicative)",
      value: 6.2,
      unit: "million",
      freshness: "P",
      source: "CEHRD",
      asOf: "AY 2082",
      format: "raw",
    },
    {
      key: "gpi",
      label: "Gender parity (basic)",
      value: 1.01,
      freshness: "P",
      source: "CEHRD",
      asOf: "AY 2082",
      format: "raw",
    },
    {
      key: "str",
      label: "Student–teacher ratio (basic)",
      value: 24,
      freshness: "P",
      source: "CEHRD",
      asOf: "AY 2082",
      format: "raw",
    },
    {
      key: "see_pass",
      label: "SEE pass rate",
      value: 61.8,
      unit: "%",
      freshness: "P",
      source: "NEB",
      asOf: "latest cycle",
      format: "percent",
    },
    {
      key: "edu_payments",
      label: "Education travel payments",
      value: 141.92,
      unit: "bn NPR",
      freshness: "P",
      source: "NRB services",
      asOf: "FY 2025/26",
      format: "raw",
    },
  ],
  energy: [
    {
      key: "installed",
      label: "Installed capacity",
      value: 3200,
      unit: "MW",
      freshness: "P",
      source: "NEA / DoED",
      asOf: "latest",
      format: "number",
    },
    {
      key: "hydro_share",
      label: "Hydro share of capacity",
      value: 95,
      unit: "%",
      freshness: "P",
      source: "NEA",
      asOf: "latest",
      format: "percent",
    },
    {
      key: "electrification",
      label: "Electricity access",
      value: 97,
      unit: "%",
      freshness: "P",
      source: "NEA / World Bank",
      asOf: "latest",
      format: "percent",
    },
    {
      key: "peak_demand",
      label: "Peak demand",
      value: 2200,
      unit: "MW",
      freshness: "NR",
      source: "NEA",
      asOf: "latest",
      format: "number",
    },
    {
      key: "petrol",
      label: "Petrol price (indicative)",
      value: 168,
      unit: "NPR/L",
      freshness: "NR",
      source: "NOC",
      asOf: "latest notice",
      format: "raw",
    },
    {
      key: "diesel",
      label: "Diesel price (indicative)",
      value: 155,
      unit: "NPR/L",
      freshness: "NR",
      source: "NOC",
      asOf: "latest notice",
      format: "raw",
    },
  ],
  environment: [
    {
      key: "ktm_aqi",
      label: "Kathmandu AQI (indicative)",
      value: 112,
      freshness: "RT",
      source: "WAQI / local stations",
      asOf: "live when token set",
      format: "number",
    },
    {
      key: "forest_cover",
      label: "Forest cover",
      value: 44.7,
      unit: "%",
      freshness: "P",
      source: "DoFSC / FRA",
      asOf: "latest",
      format: "percent",
    },
    {
      key: "co2_pc",
      label: "CO₂ per capita",
      value: 0.6,
      unit: "t",
      freshness: "P",
      source: "World Bank",
      asOf: "2023",
      format: "raw",
    },
    {
      key: "protected",
      label: "Protected areas",
      value: 22,
      freshness: "P",
      source: "DNPWC / LocalBoundaries",
      asOf: "static",
      format: "number",
    },
    {
      key: "monsoon_anomaly",
      label: "Monsoon rainfall vs normal",
      value: 4,
      unit: "%",
      freshness: "NR",
      source: "DHM / BIPAD",
      asOf: "season",
      format: "percent",
    },
  ],
  disasters: [
    {
      key: "quakes_30d",
      label: "Earthquakes (30d, Nepal bbox)",
      value: 0,
      freshness: "RT",
      source: "USGS",
      asOf: "live",
      format: "number",
      description: "Filled from live USGS connector",
    },
    {
      key: "flood_stations",
      label: "River stations monitored",
      value: 80,
      freshness: "NR",
      source: "BIPAD / DHM",
      asOf: "portal",
      format: "number",
    },
    {
      key: "incidents_ytd",
      label: "Hazard incidents (YTD indicative)",
      value: 3200,
      freshness: "NR",
      source: "BIPAD / Nepal Police",
      asOf: "YTD",
      format: "compact",
    },
    {
      key: "landslide_season",
      label: "Landslide season months",
      value: "Jun–Sep",
      freshness: "P",
      source: "NDRRMA",
      asOf: "climate",
      format: "raw",
    },
  ],
  tourism: [
    {
      key: "arrivals_ytd",
      label: "International arrivals (8m 2026)",
      value: 777672,
      delta: 5.58,
      deltaLabel: "YoY",
      freshness: "P",
      source: "NTB",
      asOf: "Aug 2026 YTD",
      format: "number",
    },
    {
      key: "arrivals_aug",
      label: "Arrivals (Aug 2026)",
      value: 85444,
      delta: -3.6,
      deltaLabel: "YoY",
      freshness: "P",
      source: "NTB",
      asOf: "Aug 2026",
      format: "number",
    },
    {
      key: "india_share",
      label: "India share of arrivals",
      value: 30.9,
      unit: "%",
      freshness: "P",
      source: "NTB",
      asOf: "Aug 2026",
      format: "percent",
    },
    {
      key: "travel_income",
      label: "Travel income",
      value: 90.05,
      unit: "bn NPR",
      freshness: "P",
      source: "NRB",
      asOf: "FY 2025/26",
      format: "raw",
    },
    {
      key: "hotels",
      label: "Hotels & resorts (indicative)",
      value: 1400,
      freshness: "P",
      source: "National Data Portal / MoCTCA",
      asOf: "latest",
      format: "compact",
    },
  ],
  digital: [
    {
      key: "mobile_subs",
      label: "Mobile subscriptions",
      value: 38.3,
      unit: "million",
      freshness: "P",
      source: "NTA MIS",
      asOf: "latest MIS",
      format: "raw",
    },
    {
      key: "voice_pen",
      label: "Voice penetration",
      value: 119.9,
      unit: "%",
      freshness: "P",
      source: "NTA",
      asOf: "Poush 2080",
      format: "percent",
    },
    {
      key: "broadband",
      label: "Broadband subscriptions",
      value: 41.3,
      unit: "million",
      freshness: "P",
      source: "NTA",
      asOf: "Poush 2080",
      format: "raw",
    },
    {
      key: "mobile_bb_share",
      label: "Mobile broadband share",
      value: 66.5,
      unit: "%",
      freshness: "P",
      source: "NTA",
      asOf: "Poush 2080",
      format: "percent",
    },
    {
      key: "fixed_bb",
      label: "Fixed broadband subs",
      value: 13.8,
      unit: "million",
      freshness: "P",
      source: "NTA",
      asOf: "Poush 2080",
      format: "raw",
    },
  ],
  transport: [
    {
      key: "vehicles",
      label: "Registered vehicles (stock)",
      value: 4.5,
      unit: "million",
      freshness: "P",
      source: "DoTM",
      asOf: "latest",
      format: "raw",
    },
    {
      key: "ev_share",
      label: "New EV share (policy focus)",
      value: 12,
      unit: "%",
      freshness: "P",
      source: "DoTM / MoFE",
      asOf: "indicative",
      format: "percent",
    },
    {
      key: "road_deaths",
      label: "Road fatalities (annual ind.)",
      value: 2800,
      freshness: "P",
      source: "Nepal Police / DoTM",
      asOf: "latest year",
      format: "number",
    },
    {
      key: "air_pax",
      label: "Domestic air passengers",
      value: 3.8,
      unit: "million",
      freshness: "P",
      source: "CAAN",
      asOf: "latest year",
      format: "raw",
    },
  ],
  agriculture: [
    {
      key: "paddy",
      label: "Paddy production",
      value: 5.6,
      unit: "million MT",
      freshness: "P",
      source: "MoALD",
      asOf: "latest season",
      format: "raw",
    },
    {
      key: "maize",
      label: "Maize production",
      value: 3.0,
      unit: "million MT",
      freshness: "P",
      source: "MoALD",
      asOf: "latest season",
      format: "raw",
    },
    {
      key: "wheat",
      label: "Wheat production",
      value: 2.1,
      unit: "million MT",
      freshness: "P",
      source: "MoALD",
      asOf: "latest season",
      format: "raw",
    },
    {
      key: "rice_price",
      label: "Rice (coarse) price",
      value: 68,
      unit: "NPR/kg",
      freshness: "NR",
      source: "Kalimati / CPI",
      asOf: "indicative",
      format: "raw",
    },
    {
      key: "oil_price",
      label: "Mustard oil price",
      value: 285,
      unit: "NPR/L",
      freshness: "NR",
      source: "Market / CPI",
      asOf: "indicative",
      format: "raw",
    },
    {
      key: "livestock",
      label: "Cattle & buffalo (stock)",
      value: 12.5,
      unit: "million",
      freshness: "P",
      source: "MoALD",
      asOf: "latest",
      format: "raw",
    },
  ],
  migration: [
    {
      key: "approvals_fy",
      label: "Labor approvals (FY ind.)",
      value: 750000,
      freshness: "P",
      source: "DoFE",
      asOf: "latest FY",
      format: "compact",
    },
    {
      key: "dest_gulf",
      label: "Gulf destinations share",
      value: 58,
      unit: "%",
      freshness: "P",
      source: "DoFE",
      asOf: "latest",
      format: "percent",
    },
    {
      key: "dest_malaysia",
      label: "Malaysia share",
      value: 18,
      unit: "%",
      freshness: "P",
      source: "DoFE",
      asOf: "latest",
      format: "percent",
    },
    {
      key: "remit_link",
      label: "Remittance (same as economy)",
      value: 2363.13,
      unit: "bn NPR",
      freshness: "P",
      source: "NRB",
      asOf: "FY 2025/26",
      format: "raw",
    },
    {
      key: "absent_pop",
      label: "Absent population (census)",
      value: 2.2,
      unit: "million",
      freshness: "P",
      source: "NPHC 2021",
      asOf: "2021",
      format: "raw",
    },
  ],
  places: [],
  news: [],
};

/** Approximate district populations scaled to census total (illustrative choropleth). */
export const DISTRICT_POPULATION: Record<string, number> = {
  KATHMANDU: 2049656,
  MORANG: 1148555,
  RUPANDEHI: 1121486,
  JHAPA: 994090,
  SUNSARI: 926576,
  KASKI: 601894,
  CHITWAN: 719859,
  LALITPUR: 551667,
  BHAKTAPUR: 430683,
  PARSA: 654543,
  BARA: 763137,
  DANG: 674093,
  BAITADI: 242157,
  BAJHANG: 189098,
  BAJURA: 138998,
  BANKE: 603194,
  BARDIYA: 459984,
  DADELDHURA: 142094,
  DAILEKH: 261770,
  DARCHULA: 133274,
  DHADING: 325861,
  DOLAKHA: 172767,
  DOLPA: 42789,
  DOTI: 204831,
  GORKHA: 252201,
  GULMI: 246494,
  HUMLA: 55553,
  ILAM: 279534,
  JAJARKOT: 189233,
  JUMLA: 118349,
  KALIKOT: 145292,
  KAPILVASTU: 682961,
  KAILALI: 911155,
  KANCHANPUR: 513871,
  LAMJUNG: 155288,
  MAHOTTARI: 706635,
  MAKWANPUR: 456304,
  MANANG: 5668,
  MUSTANG: 14526,
  MYAGDI: 107073,
  NAWALPARASI_E: 405939,
  NAWALPARASI_W: 383512,
  NUWAKOT: 263391,
  OKHALDHUNGA: 139758,
  PALPA: 245027,
  PANCHTHAR: 172400,
  PARBAT: 130887,
  PYUTHAN: 232019,
  RAMECHHAP: 170230,
  RASUWA: 46768,
  RAUTAHAT: 813384,
  ROLPA: 234793,
  RUKUM_E: 56868,
  RUKUM_W: 166740,
  SALYAN: 238515,
  SANKHUWASABHA: 159203,
  SAPTARI: 706255,
  SARLAHI: 862470,
  SINDHULI: 300027,
  SINDHUPALCHOK: 262371,
  SIRAHA: 739977,
  SOLUKHUMBU: 104926,
  SURKHET: 415126,
  SYANGJA: 253024,
  TANAHU: 323288,
  TAPLEJUNG: 120590,
  TERHATHUM: 88731,
  UDAYAPUR: 342523,
  ACHHAM: 228852,
  ARGHAKHANCHI: 177086,
  BAGLUNG: 249211,
  BHOJPUR: 157923,
  DHANKUTA: 150599,
  DHANUSA: 876503,
  KAVREPALANCHOK: 364039,
  KHOTANG: 206312,
  MUGU: 55396,
};

export const TOURISM_BY_COUNTRY = [
  { country: "India", arrivals: 26373 },
  { country: "China", arrivals: 10304 },
  { country: "Sri Lanka", arrivals: 8710 },
  { country: "USA", arrivals: 6293 },
  { country: "Bangladesh", arrivals: 4487 },
];

export const AGE_PYRAMID = [
  { band: "0-4", male: 1.32, female: 1.24 },
  { band: "5-9", male: 1.45, female: 1.36 },
  { band: "10-14", male: 1.52, female: 1.44 },
  { band: "15-19", male: 1.48, female: 1.46 },
  { band: "20-24", male: 1.35, female: 1.42 },
  { band: "25-29", male: 1.18, female: 1.3 },
  { band: "30-34", male: 1.05, female: 1.18 },
  { band: "35-39", male: 0.95, female: 1.05 },
  { band: "40-44", male: 0.85, female: 0.92 },
  { band: "45-49", male: 0.75, female: 0.8 },
  { band: "50-54", male: 0.65, female: 0.68 },
  { band: "55-59", male: 0.52, female: 0.55 },
  { band: "60-64", male: 0.42, female: 0.45 },
  { band: "65+", male: 0.95, female: 1.05 },
];

export const CALENDAR_EVENTS = [
  { date: "2026-09-01", title: "NRB monthly macro (typical)", type: "economy" },
  { date: "2026-10-01", title: "Dashain festival period", type: "holiday" },
  { date: "2026-11-01", title: "Tihar festival period", type: "holiday" },
  { date: "2026-12-15", title: "MoF mid-year review window", type: "fiscal" },
  { date: "2027-05-29", title: "Republic Day", type: "holiday" },
];
